######################## default configuration ####################
baseURL = "https://examplesite.com"
languageCode = "en"
title = "WEFPCO | Western Ghat Farmer Producer Company"
theme = "hargo"
summaryLength = "20"
paginate = 10
disqusShortname = ""
 
############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  link = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  link = "plugins/slick/slick.css"
  [[params.plugins.css]]
  link = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  link = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  link = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  link = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  link = "plugins/google-map/gmap.js"


############################## navigation ###############################
[menu]

  #[[menu.main]]
  #name = "Services"
  #URL = "services"
  #weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 1

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 2

  ############# footer menu #############
  #[[menu.footer]]
  #name = "Services"
  #URL = "services"
  #weight = 1

  [[menu.footer]]
  name = "Blog"
  URL = "blog"
  weight = 1

  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 2

  #[[menu.footer]]
  #name = "Terms & Conditions"
  #URL = "terms-conditions"
  #weight = 3


#################### default parameters ################################
[params] 
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Shyam Sreevalsan"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "11.24311517217739"
mapLongitude = "75.78543845298105"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "" # Your ID
# Contact Information
mobile = "+919388110491, +919895602061, +919447784367"
email = "emailwefpcoindia@gmail.com"
location = "Kozhikode, Kerala, India"
# copyright
copyright = "| Copyright &copy; 2020 WEFPCO Ltd |"
# Snipcart Credentials
#snipcartApiKey = "M2E5YjA3NjMtYzRiYS00YzVjLWEyYWYtNDY5ZDI0OWZhYjg5"
#currencySymbol = "$"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Product Rating
  # it works with https://rating-widget.com/ , you will get the ID and publicKey after creating your account there.
  [params.rating]
  enable = false
  websiteID = "444334"
  publicKey = "811cf0927332bf51f2e12f84608594ac"

  # Social Site
  [[params.social]]
  icon = "ti-facebook" 
  link = "#"

  [[params.social]]
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  icon = "ti-youtube"
  link = "#"

  [[params.social]]
  icon = "ti-instagram"
  link = "#"

  # Contact Form
  [params.contact]
  formAction = "https://formspree.io/f/xgepnjnp" # contact form works with formspree.io
